apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registryqjf0706.azurecr.io/tripinsights/userjava:1.0
        imagePullPolicy: Always
        envFrom:
            - secretRef:
                name: dbpass
        ports:
        - containerPort: 80
    