apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip-viewer
  template:
    metadata:
      labels:
        app: trip-viewer
    spec:
      containers:
      - name: trip-viewer
        image: registryqjf0706.azurecr.io/tripinsights/tripviewer:1.0
        imagePullPolicy: Always
        env:
          - name: USERPROFILE_API_ENDPOINT
            value: "http://user-profile.api.svc.cluster.local"
          - name: TRIPS_API_ENDPOINT
            value: "http://trips-api.api.svc.cluster.local"
        ports:
        - containerPort: 80
    