apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips-api
  template:
    metadata:
      labels:
        app: trips-api
    spec:
      containers:
      - name: trips-api
        image: registryqjf0706.azurecr.io/tripinsights/trips:1.0
        imagePullPolicy: Always
        envFrom:
            - secretRef:
                name: dbpass
        ports:
        - containerPort: 80
    