apiVersion: v1
kind: ConfigMap
metadata:
  name: user-profile-config
data:
  SQL_USER: "sqladminqJf0706"
  SQL_PASSWORD: ""
  SQL_SERVER: "sqlserverqjf0706.database.windows.net"
  SQL_DBNAME: "mydrivingDB"
  ASPNETCORE_ENVIRONMENT: "Local"